### ISSUE TITLE
Как сгенерировать URL для перенаправления пользователя на оплату?

### ISSUE THREAD

**Issue by Finesse** [Platron/php-sdk#1]
Как с помощью SDK сгенерировать URL, на который надо перенаправить пользователя, чтобы [инициализировать платёж через браузер пользователя](https://front.platron.ru/docs/api/initialize_payment/throught_browser/)?

**Comment by lashnag** [comment]
Добрый день! Используйте метод InitPaymentBuilder как в примере. В ответе будет xml, в котором содержится ссылка куда надо отправить пользователя https://front.platron.ru/docs/api/initialize_payment/host-to-host/

**Comment by Finesse** [comment]
@lashnag Нет, это не то. Нужен не «host-to-host», а именно «через браузер пользователя».

**Comment by lashnag** [comment]
Вы в любом случае подпись генерируете в бекэнде. Поэтому там же вместо генерации ссылки можно сделать запрос host-to-host и в ответе получить ссылку. И дальше отправить браузер по адресу в ответе.
Если Вам нужно по другому как-то сделать - позвоните в офис (скажите соединить с Алексеем) - объясните почему вы хотите сделать по другому.

**Comment by Finesse** [comment]
@lashnag Я не в Москве, а у вас нет номера 8800, поэтому разберусь сам.

Получить URL для перенаправления покупателя можно так:

```php
$requestBuilder = new \Platron\PhpSdk\request\request_builders\InitPaymentBuilder('10.00', 'Test transaction');
$requestBuilder->addTestingMode()
    ->addUserEmail('test@test.ru')
    ->addUserPhone('79055770000')
    ->addPaymentSystem('TEST');

$url = $requestBuilder->getRequestUrl();
$parameters = $requestBuilder->getParameters();
$parameters['pg_merchant_id'] = /* идентификатор магазина */;
$parameters['pg_salt'] = rand(21,43433);
$parameters['pg_sig'] = (new \Platron\PhpSdk\SigHelper(/* секрет */))->make(pathinfo($url)['basename'], $parameters);

$redirectURL = $url.'?'.http_build_query($parameters);
```

Было бы здорово вынести код, генерирующий адрес и тело запроса из `PostClient::request` в отдельный метод, например, `PostClient::getRequestAttributes`. Тогда можно было бы делать так:

```php
$client = new \Platron\PhpSdk\request\clients\PostClient(/* идентификатор магазина */, /* секрет */);
$requestBuilder = /* ... */;
$requestAttributes = $client->getRequestAttributes($request);
$redirectURL = $requestAttributes['url'].'?'.$requestAttributes['content'];
```

**Comment by lashnag** [comment]
@FinesseRus Вам не нужно выносить никакие аттрибуты (я уж не говорю про возврат массива из метода). Вам нужно сделать запрос так, как написано в примере. Дальше сделать редирект пользователя по pg_redirect_url из xml.

**Comment by Finesse** [comment]
@lashnag Почему вы так настаиваете на методе host-to-host? Я понимаю, что я могу сделать запрос на сервер Platron и получить адрес для перенаправления, вопрос не про это. Судя по [документации](https://front.platron.ru/docs/api/initialize_payment/), у меня есть выбор между двумя способами инициализации платежа, меня интересует именно способ «Через браузер пользователя». Я уже выяснил, что SDK не имеет метод для генерации URL для этого способа.

**Comment by lashnag** [comment]
@FinesseRus Дело в том, что SDK делает именно запросы. Т.е. SDK инкапсулирует все нижнеуровневое общение с Platron. Поэтому он не реализует метод инициализации транзакции посредством браузера. Я как раз пытаюсь понять почему вы не можете пользоваться инициализацией транзакции host-to-host

**Comment by Finesse** [comment]
@lashnag Понятно, спасибо.

> Я как раз пытаюсь понять почему вы не можете пользоваться инициализацией транзакции host-to-host

Могу, но предпочитаю альтернативный способ, потому что дополнительный HTTP-запрос это: увеличенное время ответа покупателю, нагрузка на сервер/сеть и источник потенциальных ошибок (снижение надёжности системы). Избавиться от этих недостатков — мелочь, а приятно.
