### ISSUE TITLE
$callback->validateSig() всегда возвращает false

### ISSUE THREAD

**Issue by Alexxosipov** [Platron/php-sdk#12]
Создаю новый платеж:
```
$client = new PostClient($shopCode, $shopSecret);
$plan = Plan::find(2);
        try {
            $requestBuilder = new InitPaymentBuilder($plan->price, $plan->name);
            $requestBuilder->addTestingMode()
                ->addOrderId($user->id)
                ->addPaymentSystem('TEST');
            $response = $client->request($requestBuilder);
            return redirect()->to($response->pg_redirect_url);
        }
        catch (Exception $e){
            dd($e);
        }
```
Далее, хочу получить ответ об успешной оплате:
```
    public function platronHandle(Request $request)
    {
        $callback = new Callback('platron/handle', $secretKey);
        $req = $request->all();
        Log::info('request', $req);
        Log::info('Is valid:', [$callback->validateSig($req)]);
    }
```
Но в логах `Is valid` всегда равняется false.
В `$request->all()` приходят следующие данные:
```
array (
  'pg_salt' => '76f4ea',
  'pg_order_id' => '250534861',
  'pg_payment_id' => '47217116',
  'pg_amount' => '19.0000',
  'pg_currency' => 'RUB',
  'pg_net_amount' => '19',
  'pg_ps_amount' => '19',
  'pg_ps_full_amount' => '19.00',
  'pg_ps_currency' => 'RUB',
  'pg_payment_system' => 'TEST',
  'pg_result' => '1',
  'pg_payment_date' => '2019-04-06 14:25:17',
  'pg_can_reject' => '0',
  'pg_user_phone' => '213123123123',
  'pg_need_phone_notification' => '1',
  'sdk' => 'phpsdk',
  'pg_sig' => 'cc8dfc2a42c1b8080858524f9cc43ee0',
)
```
В ЛК platron вижу, что отправляются те же данные:
```
Array
(
    [pg_salt] => 76f4ea
    [pg_order_id] => 250534861
    [pg_payment_id] => 47217116
    [pg_amount] => 19.0000
    [pg_currency] => RUB
    [pg_net_amount] => 19
    [pg_ps_amount] => 19
    [pg_ps_full_amount] => 19.00
    [pg_ps_currency] => RUB
    [pg_payment_system] => TEST
    [pg_result] => 1
    [pg_payment_date] => 2019-04-06 14:25:17
    [pg_can_reject] => 0
    [pg_user_phone] => 213123123123
    [pg_need_phone_notification] => 1
    [sdk] => phpsdk
    [pg_sig] => cc8dfc2a42c1b8080858524f9cc43ee0
)
```
Но метод `$callback->validateSig($req)` возвращает false. URL скрипта (platron/handle) правильный, поскольку вот URL из личного кабинета, на который посылается запрос: `https://d3e7****.ngrok.io/platron/handle`

Что я делаю не так? Похоже на какой-то баг, поскольку делал все по докам

**Comment by lashnag** [comment]
Добрый день! Видимо, вы неправильно указываете имя скрипта при callback. https://front.platron.ru/docs/api/common_rules/ - согласно общим правилам скрипт должен 'handle', а не 'platron/handle'
Проверьте, пожалуйста

**Comment by Alexxosipov** [comment]
> Добрый день! Видимо, вы неправильно указываете имя скрипта при callback. https://front.platron.ru/docs/api/common_rules/ - согласно общим правилам скрипт должен 'handle', а не 'platron/handle'
> Проверьте, пожалуйста

Да, верно. Поправьте это в phpdoc метода `validateSig()`, поскольку там не написано, что нужно писать от последнего `/` или `?`, вводит в заблуждение. Каюсь, саму доку не читал, поскольку посчитал phpdoc самодостаточным
