### ISSUE TITLE
Ошибка из-за неправильного использования метода LoggerInterface::Log

### ISSUE THREAD

**Issue by Finesse** [Platron/php-sdk#2]
Если в объекте `PostClient` задан логгер (например, логгер из Laravel), то вызов метода `request` приводит к ошибке на подобии «неверное значение аргумента $level».

Немного поковыряв код, я выяснил следующее. Файл `src/request/clients/PostClient.php`, строка 66:

```php
$this->logger->log(self::LOG_LEVEL, 'Request url '.$requestBuilder->getRequestUrl().' with params '.print_r($parameters, true));
$this->logger->log(self::LOG_LEVEL, 'Response '.$response);
```

При вызове метода `LoggerInterface::Log` ему в качестве первого аргумента передаётся константа `self::LOG_LEVEL`, которая имеет значение `0` (число). В стандарте PSR-логгера есть [набор констант](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#5-psrlogloglevel), обозначающих уровни логирования, все они являются строками, содержащими названия уровней. Логгер ожидает строку, а получает число, из-за этого вызывает исключение.

Предлагаю такое решение: в файле `src/request/clients/PostClient.php` в строке 13 заменить
```php
const LOG_LEVEL = 0;
``` 
на 
```php
const LOG_LEVEL = \Psr\Log\LogLevel::DEBUG;
```

**Comment by lashnag** [comment]
Спасибо! Внесу изменения, только скорее всего там должно быть INFO. Так как логирование может быть не только в режиме отладки

**Comment by Finesse** [comment]
@lashnag Спасибо
