### ISSUE TITLE
Метод Callback::validateSig вызывает ошибку, если в массиве $params нет ключа pg_sig

### ISSUE THREAD

**Issue by Finesse** [Platron/php-sdk#3]
Как воспроизвести:

```php
$request = [
    'foo' => 'bar',
    'iam' => 'hacker'
];
$callback = new platron_sdk\callback\Callback('platron_dispatch.php', 'sdvsfdvsfdvsdv');
$isValid = $callback->validateSig($request);
```

В результате возникает ошибка `Undefined index: pg_sig`.

Ещё можно вызвать ошибку так:

```php
// Это содержимое $_GET или $_POST для запроса pg_sig[foo]=bar
$request = [
    'pg_sig' => ['foo' => 'bar']
];
$callback = new platron_sdk\callback\Callback('platron_dispatch.php', 'sdvsfdvsfdvsdv');
$isValid = $callback->validateSig($request);
```

Предлагаю решение: в файле `src/callback/Callback.php` в строке 44 заменить
```php
return $this->sigHelper->check($params['pg_sig'], $this->urlScriptName, $params);
```
на
```php
return isset($params['pg_sig']) && is_scalar($params['pg_sig']) && $this->sigHelper->check($params['pg_sig'], $this->urlScriptName, $params);
```

**Comment by lashnag** [comment]
Думаю можно проверить это снаружи

**Comment by Finesse** [comment]
@lashnag Можно, но вы хоть напишите, что `Callback::validateSig` требует не просто массив, а массив, в котором есть определённый индекс.

Я думаю, будет рациональней добавить эту проверку один раз в SDK, чем писать эту проверку при каждом использовании метода. Тем более, что подобные проверки уже есть в остальных местах класса (строки 52, 62, 72 и 81).

**Comment by lashnag** [comment]
Можно все запихнуть внутрь, чтобы 2 параметра были при вызове. Так Вам будет удобно?

**Comment by Finesse** [comment]
@lashnag Не понимаю, что вы имеете ввиду. Покажите пример.

**Comment by Finesse** [comment]
@lashnag Метод `validateSig` проверяет подпись запросов. Значит, он вызывается при любом запросе (даже не подписанном). Значит, в него могут попасть любые данные из запроса. Значит, он требует осторожности в обращении с входными параметрами. 

Остальные методы вызываются после успешной проверки подписи, значит, в них не могут попасть параметры в неожиданном формате и они не требуют тщательного обращения с аргументами.

**Comment by lashnag** [comment]
Нет, я имею ввиду, что наличие подписи во входящих параметрах и то, что он строка буду проверять внутри validateSig. Как вы на это смотрите?

**Comment by Finesse** [comment]
@lashnag Я за. Я, вроде, так и предлагал сделать.

**Comment by lashnag** [comment]
Прошу прощения, я сразу не въехал. Сделал фикс и новый релиз. Спасибо!

**Comment by Finesse** [comment]
@lashnag Вам спасибо
