### ISSUE TITLE
Вызов ReceiptBuilder::addItem всегда приводит к ошибке

### ISSUE THREAD

**Issue by Finesse** [Platron/php-sdk#4]
Вызов метода `Platron\PhpSdk\request\request_builders\ReceiptBuilder::addItem` приводит к ошибке `Use of undefined constant self - assumed 'self'`.

Пример как воспроизвести:

```php
use Platron\PhpSdk\request\request_builders\ReceiptBuilder;
use Platron\PhpSdk\request\data_objects\Item

$request = new ReceiptBuilder(ReceiptBuilder::TRANSACTION_TYPE, 123);
$request->addItem(new Item('Шуба', 10000, 1);
```

Эта ошибка, кстати, воспроизводится, если запустить unit-тесты.

### Расследование

Код этого метода:

```php
/**
 * Добавить позицию чека
 * @param Item $item
 * @return self
 */
public function addItem(Item $item){
    $this->items[] = $item;
    return self;
}
```

PHP не позволяет возвращать `self`. Судя по всему, метод должен возвращать `$this`. В комментарии к методу тоже лучше указать  `@return $this`, так PhpStorm будет лучше понимать семантику метода.

**Comment by lashnag** [comment]
Спасибо за помощь!

**Comment by Finesse** [comment]
@lashnag И вам спасибо за быстрое решение проблем
